geekshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.ProductCategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductView.as_view(), name='products'),
#    path('products/read/<int:pk>/', adminapp.ProductListView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),

    path('orders/read/', adminapp.OrderListView.as_view(), name='orders'),
    path('orders/update/<int:pk>/', adminapp.OrderUpdateView.as_view(), name='order_update'),
    path('orders/delete/<int:pk>/', adminapp.OrderDeleteView.as_view(), name='order_delete'),
]

geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<slug:activation_key>/', authapp.verify, name='verify'),
    path('send_invite/<email>', authapp.send_invite, name='send_invite'),
]     

geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.urls import path
from django.contrib import admin
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

#if settings.DEBUG:
#    import debug_toolbar


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', admin.site.urls),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('social/', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

geekshop/mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.products, name='index'),
   path('category/<int:pk>/', mainapp.products, name='category'),
   path('category/<int:pk>/ajax/', cache_page(3600)(mainapp.products_ajax)),
   path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
   path('category/<int:pk>/page/<int:page>/ajax/', cache_page(3600)(mainapp.products_ajax)),
   path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import path

app_name="ordersapp"

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
    path('price/<int:pk>/', ordersapp.product_price, name='product_price')
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)
    image = models.ImageField(upload_to='category_images', blank=True)
    is_active = models.BooleanField(verbose_name='активен', default=True, db_index=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.TextField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активен', default=True, db_index=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @staticmethod
    def get_item(pk):
        return Product.objects.filter(pk=pk).first()

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

geekshop/mainapp/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render
from django.conf import settings
from django.core.cache import cache
from django.template.loader import render_to_string

from .models import ProductCategory, Product
from django.shortcuts import get_object_or_404
import random


main_links_menu = [
        {'href': 'main', 'name': 'Главная'},
        {'href': 'products:index', 'name': 'Продукты'},
        {'href': 'contact', 'name': 'Контакты'}
    ]


def get_hot_product():
    _products = get_products()
    return random.sample(list(_products), 1)[0]

    
def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]

    return same_products

def main(request):
    title = 'Главная'
    content = {
            'title': title,
            'links_menu': main_links_menu,          
        }
    return render(request, 'mainapp/index.html', content)


def products(request, pk=None, page=1):
    title = 'Категории'
    categories = get_categories()
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    if pk is not None:
        if pk == 0:
            _products = get_products_orederd_by_price()
            category = {
                'name': 'Все',
                'pk': '0'
            }
        else:
            category = get_category(pk)
            _products = get_products_in_category_orederd_by_price(pk)
        paginator = Paginator(_products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)
        content = {
            'title': title,
            'links_menu': main_links_menu,
            'category': category,
            'products': products_paginator,
            'categories': categories,
            'same_products': same_products,
            'hot_product': hot_product,
        }
        return render(request, 'mainapp/products.html', content)
    content = {
        'title': title, 
        'links_menu': main_links_menu, 
        'same_products': same_products,
        'categories': categories,
        'hot_product': hot_product,
    }
    return render(request, 'mainapp/catalog.html', content)


def products_ajax(request, pk=None, page=1):
    if request.is_ajax():
        title = 'Категории'
        categories = get_categories()
        hot_product = get_hot_product()
        same_products = get_same_products(hot_product)
        if pk is not None:
            if pk == 0:
                _products = get_products_orederd_by_price()
                category = {
                    'name': 'Все',
                    'pk': '0'
                }
            else:
                category = get_category(pk)
                _products = get_products_in_category_orederd_by_price(pk)
            paginator = Paginator(_products, 2)
            try:
                products_paginator = paginator.page(page)
            except PageNotAnInteger:
                products_paginator = paginator.page(1)
            except EmptyPage:
                products_paginator = paginator.page(paginator.num_pages)
            content = {
                'title': title,
                'links_menu': main_links_menu,
                'category': category,
                'products': products_paginator,
                'categories': categories,
                'same_products': same_products,
                'hot_product': hot_product,
            }
            result = render_to_string(
                'mainapp/includes/inc_products_list_content.html',
                context=content,
                request=request)
            return JsonResponse({'result': result})


def contact(request):
    title = 'Контакты'
    content = {
            'title': title,
            'links_menu': main_links_menu,
        }
    return render(request, 'mainapp/contacts.html', content)

def product(request, pk):
    title = 'продукты'
    content = {
        'title': title,
        'links_menu': main_links_menu,
        'categories': get_categories(),
        'product': get_object_or_404(Product, pk=pk), 
    }
    
    return render(request, 'mainapp/product.html', content)

def get_categories():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        _products = cache.get(key)
        if _products is None:
            _products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, _products)
        return _products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        _products = cache.get(key)
        if _products is None:
            _products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, _products)
        return _products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        _products = cache.get(key)
        if _products is None:
            _products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')
            cache.set(key, _products)
        return _products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')

geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
  <li>
    <a href="{% url 'products:category' 0 %}" 
       class="{% if request.resolver_match.kwargs.pk == 0 %}
                menu-link-active
              {% endif %}">
      Все
    </a>
  </li>
  {% for category in categories %}
    <li>
      <a href="{% url 'products:category' category.pk %}" 
         class="{% if request.resolver_match.kwargs.pk|add:'0' == category.pk %}
                  menu-link-active
                {% endif %}">
        {{ category.name }}
      </a>
    </li>
  {% endfor %}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_menu.html
{% load staticfiles %}
{% load custom_tags %}
<div class="header">
    <a href="{% url 'main' %}"><img src="{% static 'img/logotip.png' %}" alt="logo" class="logotip"></a>
    <ul class="main-menu">
        {% for link in links_menu %}
            <li class="menu-list"><a
                    class="menu-link {% if request.resolver_match.view_name == link.href %}menu-link-active {% endif %}"
                                     href="{% url link.href %}">{{ link.name }}</a></li>
        {% endfor %}
        {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                <a class="dropdown-toggle" href="" data-toggle="dropdown">
                    {{ user.first_name|default:'Пользователь' }}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'auth:edit' %}">
                            профиль
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'ordersapp:orders_list' %}">
                            заказы
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        {% endif %}

        {% if user.is_superuser %}
            <li class="menu-list">
            <a href="{% url 'admin_custom:users' %}">админка</a>
            </li>
        {% endif %} 
        <li class="menu-list">
            {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}" class="menu-link">выйти</a>
            {% else %}
            <a href="{% url 'auth:login' %}" class="menu-link">войти</a>
            или
            <a href="{% url 'auth:register' %}" class="menu-link">Зарегистрироваться</a>
            {% endif %}
            {% if basket %}
            <a href="{% url 'basket:view' %}" class="menu-link">
                {{ request.user|basket_total_cost }} руб 
                ({{ request.user|total_quantity }} шт)
            </a>
            {% endif %}
        </li>
    </ul>
</div>

geekshop/mainapp/templates/mainapp/includes/inc_products_list_content.html
{% load staticfiles %}

<h1>{{ category.name }}</h1>
{% include 'mainapp/includes/inc_categories_menu.html' %}
        <div class="paginator">
          {% if products.has_previous %}
            <a href="{% url 'products:page' category.pk products.previous_page_number %}"><</a>
          {% endif %}
          <span class="current">
            страница {{ products.number }} из
            {{ products.paginator.num_pages }}
          </span>
          {% if products.has_next %}
            <a href="{% url 'products:page' category.pk products.next_page_number %}">></a>
          {% endif %}
        </div>
<div class="catalog">
    <div class="category-products clearfix">
        {% for product in products %}
            <div class="product-block">
            <a href="{% url 'products:product' product.pk %}">
                <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}", width="100">
                <div class="text">
                {% comment %} <img src="{% static 'img/icon-hover.png' %}" alt="hover"> {% endcomment %}
                <h4>{{ product.name }}</h4>
                <p>{{ product.description }} </p>
                </div>
            </a>
            </div>
        {% endfor %}
    </div>
</div>